"""Add age constraint to student

Revision ID: 356bfa3e5deb
Revises: b39306de9d0a
Create Date: 2025-08-27 01:50:38.815681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356bfa3e5deb'
down_revision = 'b39306de9d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('reg_code',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_constraint('StudentRegNoUK', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_unique_constraint('StudentRegNoUK', ['reg_code'])
        batch_op.alter_column('reg_code',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
