"""Add boarding house FK

Revision ID: 839be272fa81
Revises: 356bfa3e5deb
Create Date: 2025-08-27 02:13:57.540353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839be272fa81'
down_revision = '356bfa3e5deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boarding_house', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("StudentBoardingHouseFK", 'boarding_houses', ['boarding_house'], ['id'])
        batch_op.create_check_constraint("AgeGreaterEqual5", "age >=5")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint("StudentBoardingHouseFK", type_='foreignkey')
        batch_op.drop_constraint("AgeGreaterEqual5")
        batch_op.drop_column('boarding_house')

    # ### end Alembic commands ###
